export default {
    1: {
        number: 1,
        name: "Bulbasaur",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Bulbasaur_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/e/ec/001MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/2/21/001Bulbasaur.png/250px-001Bulbasaur.png",
    },
    2: {
        number: 2,
        name: "Ivysaur",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Ivysaur_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/6b/002MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/73/002Ivysaur.png/250px-002Ivysaur.png",
    },
    3: {
        number: 3,
        name: "Venusaur",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Venusaur_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/df/003MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/ae/003Venusaur.png/250px-003Venusaur.png",
    },
    4: {
        number: 4,
        name: "Charmander",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Charmander_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/b/bb/004MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/73/004Charmander.png/250px-004Charmander.png",
    },
    5: {
        number: 5,
        name: "Charmeleon",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Charmeleon_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/dc/005MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/4a/005Charmeleon.png/250px-005Charmeleon.png",
    },
    6: {
        number: 6,
        name: "Charizard",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Charizard_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/01/006MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/7e/006Charizard.png/250px-006Charizard.png",
    },
    7: {
        number: 7,
        name: "Squirtle",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Squirtle_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/92/007MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/39/007Squirtle.png/250px-007Squirtle.png",
    },
    8: {
        number: 8,
        name: "Wartortle",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Wartortle_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/f3/008MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/0c/008Wartortle.png/250px-008Wartortle.png",
    },
    9: {
        number: 9,
        name: "Blastoise",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Blastoise_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/cb/009MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/02/009Blastoise.png/250px-009Blastoise.png",
    },
    10: {
        number: 10,
        name: "Caterpie",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Caterpie_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/69/010MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/5/5d/010Caterpie.png/250px-010Caterpie.png",
    },
    11: {
        number: 11,
        name: "Metapod",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Metapod_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/ce/011MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/cd/011Metapod.png/250px-011Metapod.png",
    },
    12: {
        number: 12,
        name: "Butterfree",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Butterfree_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/14/012MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/d1/012Butterfree.png/250px-012Butterfree.png",
    },
    13: {
        number: 13,
        name: "Weedle",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Weedle_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/65/013MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/df/013Weedle.png/250px-013Weedle.png",
    },
    14: {
        number: 14,
        name: "Kakuna",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Kakuna_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/8/81/014MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/f0/014Kakuna.png/250px-014Kakuna.png",
    },
    15: {
        number: 15,
        name: "Beedrill",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Beedrill_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/5a/015MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/61/015Beedrill.png/250px-015Beedrill.png",
    },
    16: {
        number: 16,
        name: "Pidgey",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Pidgey_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/9c/016MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/5/55/016Pidgey.png/250px-016Pidgey.png",
    },
    17: {
        number: 17,
        name: "Pidgeotto",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Pidgeotto_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/a9/017MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/7a/017Pidgeotto.png/250px-017Pidgeotto.png",
    },
    18: {
        number: 18,
        name: "Pidgeot",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Pidgeot_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/68/018MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/5/57/018Pidgeot.png/250px-018Pidgeot.png",
    },
    19: {
        number: 19,
        name: "Rattata",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Rattata_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/4d/019MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/46/019Rattata.png/250px-019Rattata.png",
    },
    20: {
        number: 20,
        name: "Raticate",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Raticate_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/4d/020MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/f4/020Raticate.png/250px-020Raticate.png",
    },
    21: {
        number: 21,
        name: "Spearow",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Spearow_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/5b/021MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/8b/021Spearow.png/250px-021Spearow.png",
    },
    22: {
        number: 22,
        name: "Fearow",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Fearow_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/35/022MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/a0/022Fearow.png/250px-022Fearow.png",
    },
    23: {
        number: 23,
        name: "Ekans",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Ekans_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/0d/023MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/fa/023Ekans.png/250px-023Ekans.png",
    },
    24: {
        number: 24,
        name: "Arbok",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Arbok_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/d3/024MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/cd/024Arbok.png/250px-024Arbok.png",
    },
    25: {
        number: 25,
        name: "Pikachu",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Pikachu_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/0f/025MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/0d/025Pikachu.png/250px-025Pikachu.png",
    },
    26: {
        number: 26,
        name: "Raichu",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Raichu_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/da/026MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/88/026Raichu.png/250px-026Raichu.png",
    },
    27: {
        number: 27,
        name: "Sandshrew",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Sandshrew_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/c3/027MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/9e/027Sandshrew.png/250px-027Sandshrew.png",
    },
    28: {
        number: 28,
        name: "Sandslash",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Sandslash_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/e/e0/028MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/0b/028Sandslash.png/250px-028Sandslash.png",
    },
    29: {
        number: 29,
        name: "Nidoran♀",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Nidoran%E2%99%80_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/ab/029MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/81/029Nidoran.png/250px-029Nidoran.png",
    },
    30: {
        number: 30,
        name: "Nidorina",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Nidorina_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/d0/030MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/cd/030Nidorina.png/250px-030Nidorina.png",
    },
    31: {
        number: 31,
        name: "Nidoqueen",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Nidoqueen_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/31/031MS.png",
        subtype: "Ground",
        img: "https://cdn.bulbagarden.net/upload/thumb/b/bf/031Nidoqueen.png/250px-031Nidoqueen.png",
    },
    32: {
        number: 32,
        name: "Nidoran♂",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Nidoran%E2%99%82_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/fb/032MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/4a/032Nidoran.png/250px-032Nidoran.png",
    },
    33: {
        number: 33,
        name: "Nidorino",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Nidorino_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/0e/033MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/9f/033Nidorino.png/250px-033Nidorino.png",
    },
    34: {
        number: 34,
        name: "Nidoking",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Nidoking_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/18/034MS.png",
        subtype: "Ground",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/c6/034Nidoking.png/250px-034Nidoking.png",
    },
    35: {
        number: 35,
        name: "Clefairy",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Clefairy_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/f9/035MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/f4/035Clefairy.png/250px-035Clefairy.png",
    },
    36: {
        number: 36,
        name: "Clefable",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Clefable_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/7/75/036MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/a9/036Clefable.png/250px-036Clefable.png",
    },
    37: {
        number: 37,
        name: "Vulpix",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Vulpix_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/8/85/037MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/60/037Vulpix.png/250px-037Vulpix.png",
    },
    38: {
        number: 38,
        name: "Ninetales",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Ninetales_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/10/038MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/05/038Ninetales.png/250px-038Ninetales.png",
    },
    39: {
        number: 39,
        name: "Jigglypuff",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Jigglypuff_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/9c/039MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/3e/039Jigglypuff.png/250px-039Jigglypuff.png",
    },
    40: {
        number: 40,
        name: "Wigglytuff",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Wigglytuff_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/f1/040MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/92/040Wigglytuff.png/250px-040Wigglytuff.png",
    },
    41: {
        number: 41,
        name: "Zubat",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Zubat_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/96/041MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/da/041Zubat.png/250px-041Zubat.png",
    },
    42: {
        number: 42,
        name: "Golbat",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Golbat_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/d0/042MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/0c/042Golbat.png/250px-042Golbat.png",
    },
    43: {
        number: 43,
        name: "Oddish",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Oddish_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/a5/043MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/43/043Oddish.png/250px-043Oddish.png",
    },
    44: {
        number: 44,
        name: "Gloom",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Gloom_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/d9/044MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/2/2a/044Gloom.png/250px-044Gloom.png",
    },
    45: {
        number: 45,
        name: "Vileplume",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Vileplume_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/3e/045MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/6a/045Vileplume.png/250px-045Vileplume.png",
    },
    46: {
        number: 46,
        name: "Paras",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Paras_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/7/7a/046MS.png",
        subtype: "Grass",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/d4/046Paras.png/250px-046Paras.png",
    },
    47: {
        number: 47,
        name: "Parasect",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Parasect_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/41/047MS.png",
        subtype: "Grass",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/80/047Parasect.png/250px-047Parasect.png",
    },
    48: {
        number: 48,
        name: "Venonat",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Venonat_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/1e/048MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/ad/048Venonat.png/250px-048Venonat.png",
    },
    49: {
        number: 49,
        name: "Venomoth",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Venomoth_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/31/049MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/d3/049Venomoth.png/250px-049Venomoth.png",
    },
    50: {
        number: 50,
        name: "Diglett",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Diglett_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/8/8b/050MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/31/050Diglett.png/250px-050Diglett.png",
    },
    51: {
        number: 51,
        name: "Dugtrio",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Dugtrio_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/8/86/051MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/e/e5/051Dugtrio.png/250px-051Dugtrio.png",
    },
    52: {
        number: 52,
        name: "Meowth",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Meowth_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/50/052MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/d6/052Meowth.png/250px-052Meowth.png",
    },
    53: {
        number: 53,
        name: "Persian",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Persian_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/a7/053MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/1/13/053Persian.png/250px-053Persian.png",
    },
    54: {
        number: 54,
        name: "Psyduck",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Psyduck_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/6b/054MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/5/53/054Psyduck.png/250px-054Psyduck.png",
    },
    55: {
        number: 55,
        name: "Golduck",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Golduck_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/64/055MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/fe/055Golduck.png/250px-055Golduck.png",
    },
    56: {
        number: 56,
        name: "Mankey",
        type: "Fighting",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Mankey_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/ad/056MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/41/056Mankey.png/250px-056Mankey.png",
    },
    57: {
        number: 57,
        name: "Primeape",
        type: "Fighting",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Primeape_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/f1/057MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/9a/057Primeape.png/250px-057Primeape.png",
    },
    58: {
        number: 58,
        name: "Growlithe",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Growlithe_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/69/058MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/3d/058Growlithe.png/250px-058Growlithe.png",
    },
    59: {
        number: 59,
        name: "Arcanine",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Arcanine_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/35/059MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/b/b8/059Arcanine.png/250px-059Arcanine.png",
    },
    60: {
        number: 60,
        name: "Poliwag",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Poliwag_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/17/060MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/49/060Poliwag.png/250px-060Poliwag.png",
    },
    61: {
        number: 61,
        name: "Poliwhirl",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Poliwhirl_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/36/061MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/a9/061Poliwhirl.png/250px-061Poliwhirl.png",
    },
    62: {
        number: 62,
        name: "Poliwrath",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Poliwrath_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/5e/062MS.png",
        subtype: "Fighting",
        img: "https://cdn.bulbagarden.net/upload/thumb/2/2d/062Poliwrath.png/250px-062Poliwrath.png",
    },
    63: {
        number: 63,
        name: "Abra",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Abra_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/cf/063MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/62/063Abra.png/250px-063Abra.png",
    },
    64: {
        number: 64,
        name: "Kadabra",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Kadabra_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/b/b6/064MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/97/064Kadabra.png/250px-064Kadabra.png",
    },
    65: {
        number: 65,
        name: "Alakazam",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Alakazam_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/ca/065MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/cc/065Alakazam.png/250px-065Alakazam.png",
    },
    66: {
        number: 66,
        name: "Machop",
        type: "Fighting",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Machop_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/6c/066MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/85/066Machop.png/250px-066Machop.png",
    },
    67: {
        number: 67,
        name: "Machoke",
        type: "Fighting",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Machoke_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/0f/067MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/8e/067Machoke.png/250px-067Machoke.png",
    },
    68: {
        number: 68,
        name: "Machamp",
        type: "Fighting",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Machamp_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/1e/068MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/8f/068Machamp.png/250px-068Machamp.png",
    },
    69: {
        number: 69,
        name: "Bellsprout",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Bellsprout_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/7/7b/069MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/a2/069Bellsprout.png/250px-069Bellsprout.png",
    },
    70: {
        number: 70,
        name: "Weepinbell",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Weepinbell_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/d5/070MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/9f/070Weepinbell.png/250px-070Weepinbell.png",
    },
    71: {
        number: 71,
        name: "Victreebel",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Victreebel_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/9b/071MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/b/be/071Victreebel.png/250px-071Victreebel.png",
    },
    72: {
        number: 72,
        name: "Tentacool",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Tentacool_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/42/072MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/4e/072Tentacool.png/250px-072Tentacool.png",
    },
    73: {
        number: 73,
        name: "Tentacruel",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Tentacruel_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/fc/073MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/f6/073Tentacruel.png/250px-073Tentacruel.png",
    },
    74: {
        number: 74,
        name: "Geodude",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Geodude_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/04/074MS.png",
        subtype: "Ground",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/98/074Geodude.png/250px-074Geodude.png",
    },
    75: {
        number: 75,
        name: "Graveler",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Graveler_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/5c/075MS.png",
        subtype: "Ground",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/75/075Graveler.png/250px-075Graveler.png",
    },
    76: {
        number: 76,
        name: "Golem",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Golem_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/34/076MS.png",
        subtype: "Ground",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/f2/076Golem.png/250px-076Golem.png",
    },
    77: {
        number: 77,
        name: "Ponyta",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Ponyta_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/55/077MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/3b/077Ponyta.png/250px-077Ponyta.png",
    },
    78: {
        number: 78,
        name: "Rapidash",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Rapidash_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/66/078MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/3f/078Rapidash.png/250px-078Rapidash.png",
    },
    79: {
        number: 79,
        name: "Slowpoke",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Slowpoke_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/6a/079MS.png",
        subtype: "Psychic",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/70/079Slowpoke.png/250px-079Slowpoke.png",
    },
    80: {
        number: 80,
        name: "Slowbro",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Slowbro_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/b/b6/080MS.png",
        subtype: "Psychic",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/80/080Slowbro.png/250px-080Slowbro.png",
    },
    81: {
        number: 81,
        name: "Magnemite",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Magnemite_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/0f/081MS.png",
        subtype: "Steel",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/6c/081Magnemite.png/250px-081Magnemite.png",
    },
    82: {
        number: 82,
        name: "Magneton",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Magneton_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/0c/082MS.png",
        subtype: "Steel",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/72/082Magneton.png/250px-082Magneton.png",
    },
    83: {
        number: 83,
        name: "Farfetch'd",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Farfetch%27d_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/57/083MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/f8/083Farfetch%27d.png/250px-083Farfetch%27d.png",
    },
    84: {
        number: 84,
        name: "Doduo",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Doduo_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/fc/084MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/5/54/084Doduo.png/250px-084Doduo.png",
    },
    85: {
        number: 85,
        name: "Dodrio",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Dodrio_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/19/085MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/93/085Dodrio.png/250px-085Dodrio.png",
    },
    86: {
        number: 86,
        name: "Seel",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Seel_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/9b/086MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/1/1f/086Seel.png/250px-086Seel.png",
    },
    87: {
        number: 87,
        name: "Dewgong",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Dewgong_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/2/20/087MS.png",
        subtype: "Ice",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/c7/087Dewgong.png/250px-087Dewgong.png",
    },
    88: {
        number: 88,
        name: "Grimer",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Grimer_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/50/088MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/a0/088Grimer.png/250px-088Grimer.png",
    },
    89: {
        number: 89,
        name: "Muk",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Muk_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/b/b4/089MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/7c/089Muk.png/250px-089Muk.png",
    },
    90: {
        number: 90,
        name: "Shellder",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Shellder_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/41/090MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/40/090Shellder.png/250px-090Shellder.png",
    },
    91: {
        number: 91,
        name: "Cloyster",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Cloyster_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/b/bc/091MS.png",
        subtype: "Ice",
        img: "https://cdn.bulbagarden.net/upload/thumb/1/1d/091Cloyster.png/250px-091Cloyster.png",
    },
    92: {
        number: 92,
        name: "Gastly",
        type: "Ghost",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Gastly_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/cf/092MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/ca/092Gastly.png/250px-092Gastly.png",
    },
    93: {
        number: 93,
        name: "Haunter",
        type: "Ghost",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Haunter_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/7/71/093MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/62/093Haunter.png/250px-093Haunter.png",
    },
    94: {
        number: 94,
        name: "Gengar",
        type: "Ghost",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Gengar_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/a4/094MS.png",
        subtype: "Poison",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/c6/094Gengar.png/250px-094Gengar.png",
    },
    95: {
        number: 95,
        name: "Onix",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Onix_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/cd/095MS.png",
        subtype: "Ground",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/9a/095Onix.png/250px-095Onix.png",
    },
    96: {
        number: 96,
        name: "Drowzee",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Drowzee_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/8/8e/096MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/3e/096Drowzee.png/250px-096Drowzee.png",
    },
    97: {
        number: 97,
        name: "Hypno",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Hypno_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/98/097MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/0a/097Hypno.png/250px-097Hypno.png",
    },
    98: {
        number: 98,
        name: "Krabby",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Krabby_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/40/098MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/a7/098Krabby.png/250px-098Krabby.png",
    },
    99: {
        number: 99,
        name: "Kingler",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Kingler_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/5c/099MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/71/099Kingler.png/250px-099Kingler.png",
    },
    100: {
        number: 100,
        name: "Voltorb",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Voltorb_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/c1/100MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/da/100Voltorb.png/250px-100Voltorb.png",
    },
    101: {
        number: 101,
        name: "Electrode",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Electrode_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/69/101MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/84/101Electrode.png/250px-101Electrode.png",
    },
    102: {
        number: 102,
        name: "Exeggcute",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Exeggcute_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/a6/102MS.png",
        subtype: "Psychic",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/af/102Exeggcute.png/250px-102Exeggcute.png",
    },
    103: {
        number: 103,
        name: "Exeggutor",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Exeggutor_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/db/103MS.png",
        subtype: "Psychic",
        img: "https://cdn.bulbagarden.net/upload/thumb/2/24/103Exeggutor.png/250px-103Exeggutor.png",
    },
    104: {
        number: 104,
        name: "Cubone",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Cubone_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/2/2e/104MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/2/2a/104Cubone.png/250px-104Cubone.png",
    },
    105: {
        number: 105,
        name: "Marowak",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Marowak_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/6f/105MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/98/105Marowak.png/250px-105Marowak.png",
    },
    106: {
        number: 106,
        name: "Hitmonlee",
        type: "Fighting",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Hitmonlee_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/60/106MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/32/106Hitmonlee.png/250px-106Hitmonlee.png",
    },
    107: {
        number: 107,
        name: "Hitmonchan",
        type: "Fighting",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Hitmonchan_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/1a/107MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/a3/107Hitmonchan.png/250px-107Hitmonchan.png",
    },
    108: {
        number: 108,
        name: "Lickitung",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Lickitung_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/2/25/108MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/00/108Lickitung.png/250px-108Lickitung.png",
    },
    109: {
        number: 109,
        name: "Koffing",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Koffing_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/3f/109MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/1/17/109Koffing.png/250px-109Koffing.png",
    },
    110: {
        number: 110,
        name: "Weezing",
        type: "Poison",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Weezing_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/2/22/110MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/42/110Weezing.png/250px-110Weezing.png",
    },
    111: {
        number: 111,
        name: "Rhyhorn",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Rhyhorn_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/67/111MS.png",
        subtype: "Rock",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/9b/111Rhyhorn.png/250px-111Rhyhorn.png",
    },
    112: {
        number: 112,
        name: "Rhydon",
        type: "Ground",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Rhydon_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/ce/112MS.png",
        subtype: "Rock",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/47/112Rhydon.png/250px-112Rhydon.png",
    },
    113: {
        number: 113,
        name: "Chansey",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Chansey_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/e/ea/113MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/cd/113Chansey.png/250px-113Chansey.png",
    },
    114: {
        number: 114,
        name: "Tangela",
        type: "Grass",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Tangela_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/45/114MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/3e/114Tangela.png/250px-114Tangela.png",
    },
    115: {
        number: 115,
        name: "Kangaskhan",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Kangaskhan_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/68/115MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/4e/115Kangaskhan.png/250px-115Kangaskhan.png",
    },
    116: {
        number: 116,
        name: "Horsea",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Horsea_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/2/23/116MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/5/5a/116Horsea.png/250px-116Horsea.png",
    },
    117: {
        number: 117,
        name: "Seadra",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Seadra_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/8/81/117MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/2/26/117Seadra.png/250px-117Seadra.png",
    },
    118: {
        number: 118,
        name: "Goldeen",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Goldeen_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/9b/118MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/7b/118Goldeen.png/250px-118Goldeen.png",
    },
    119: {
        number: 119,
        name: "Seaking",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Seaking_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/8/88/119MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/6a/119Seaking.png/250px-119Seaking.png",
    },
    120: {
        number: 120,
        name: "Staryu",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Staryu_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/6/60/120MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/4f/120Staryu.png/250px-120Staryu.png",
    },
    121: {
        number: 121,
        name: "Starmie",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Starmie_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/55/121MS.png",
        subtype: "Psychic",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/cd/121Starmie.png/250px-121Starmie.png",
    },
    122: {
        number: 122,
        name: "Mr. Mime",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Mr._Mime_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/58/122MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/e/ec/122Mr._Mime.png/250px-122Mr._Mime.png",
    },
    123: {
        number: 123,
        name: "Scyther",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Scyther_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/54/123MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/b/ba/123Scyther.png/250px-123Scyther.png",
    },
    124: {
        number: 124,
        name: "Jynx",
        type: "Ice",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Jynx_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/f5/124MS.png",
        subtype: "Psychic",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/7c/124Jynx.png/250px-124Jynx.png",
    },
    125: {
        number: 125,
        name: "Electabuzz",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Electabuzz_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/7/72/125MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/de/125Electabuzz.png/250px-125Electabuzz.png",
    },
    126: {
        number: 126,
        name: "Magmar",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Magmar_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/e/e7/126MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/8c/126Magmar.png/250px-126Magmar.png",
    },
    127: {
        number: 127,
        name: "Pinsir",
        type: "Bug",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Pinsir_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/5c/127MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/71/127Pinsir.png/250px-127Pinsir.png",
    },
    128: {
        number: 128,
        name: "Tauros",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Tauros_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/95/128MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/b/b8/128Tauros.png/250px-128Tauros.png",
    },
    129: {
        number: 129,
        name: "Magikarp",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Magikarp_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/7/7c/129MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/0/02/129Magikarp.png/250px-129Magikarp.png",
    },
    130: {
        number: 130,
        name: "Gyarados",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Gyarados_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/a0/130MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/41/130Gyarados.png/250px-130Gyarados.png",
    },
    131: {
        number: 131,
        name: "Lapras",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Lapras_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/4b/131MS.png",
        subtype: "Ice",
        img: "https://cdn.bulbagarden.net/upload/thumb/a/ab/131Lapras.png/250px-131Lapras.png",
    },
    132: {
        number: 132,
        name: "Ditto",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Ditto_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/5/53/132MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/3/36/132Ditto.png/250px-132Ditto.png",
    },
    133: {
        number: 133,
        name: "Eevee",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Eevee_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/de/133MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/e/e2/133Eevee.png/250px-133Eevee.png",
    },
    134: {
        number: 134,
        name: "Vaporeon",
        type: "Water",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Vaporeon_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/b/be/134MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/fd/134Vaporeon.png/250px-134Vaporeon.png",
    },
    135: {
        number: 135,
        name: "Jolteon",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Jolteon_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/16/135MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/b/bb/135Jolteon.png/250px-135Jolteon.png",
    },
    136: {
        number: 136,
        name: "Flareon",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Flareon_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/30/136MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/d/dd/136Flareon.png/250px-136Flareon.png",
    },
    137: {
        number: 137,
        name: "Porygon",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Porygon_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/f7/137MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/6/6b/137Porygon.png/250px-137Porygon.png",
    },
    138: {
        number: 138,
        name: "Omanyte",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Omanyte_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/9/97/138MS.png",
        subtype: "Water",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/79/138Omanyte.png/250px-138Omanyte.png",
    },
    139: {
        number: 139,
        name: "Omastar",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Omastar_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/2/2a/139MS.png",
        subtype: "Water",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/43/139Omastar.png/250px-139Omastar.png",
    },
    140: {
        number: 140,
        name: "Kabuto",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Kabuto_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/1e/140MS.png",
        subtype: "Water",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/f9/140Kabuto.png/250px-140Kabuto.png",
    },
    141: {
        number: 141,
        name: "Kabutops",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Kabutops_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/08/141MS.png",
        subtype: "Water",
        img: "https://cdn.bulbagarden.net/upload/thumb/2/29/141Kabutops.png/250px-141Kabutops.png",
    },
    142: {
        number: 142,
        name: "Aerodactyl",
        type: "Rock",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Aerodactyl_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/d1/142MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/e/e8/142Aerodactyl.png/250px-142Aerodactyl.png",
    },
    143: {
        number: 143,
        name: "Snorlax",
        type: "Normal",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Snorlax_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/d/d6/143MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/f/fb/143Snorlax.png/250px-143Snorlax.png",
    },
    144: {
        number: 144,
        name: "Articuno",
        type: "Ice",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Articuno_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/0/04/144MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/4/4e/144Articuno.png/250px-144Articuno.png",
    },
    145: {
        number: 145,
        name: "Zapdos",
        type: "Electric",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Zapdos_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/3/3f/145MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/e/e3/145Zapdos.png/250px-145Zapdos.png",
    },
    146: {
        number: 146,
        name: "Moltres",
        type: "Fire",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Moltres_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/f/fe/146MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/1/1b/146Moltres.png/250px-146Moltres.png",
    },
    147: {
        number: 147,
        name: "Dratini",
        type: "Dragon",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Dratini_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/2/26/147MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/c/cc/147Dratini.png/250px-147Dratini.png",
    },
    148: {
        number: 148,
        name: "Dragonair",
        type: "Dragon",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Dragonair_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/4/4e/148MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/9/93/148Dragonair.png/250px-148Dragonair.png",
    },
    149: {
        number: 149,
        name: "Dragonite",
        type: "Dragon",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Dragonite_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/c/cc/149MS.png",
        subtype: "Flying",
        img: "https://cdn.bulbagarden.net/upload/thumb/8/8b/149Dragonite.png/250px-149Dragonite.png",
    },
    150: {
        number: 150,
        name: "Mewtwo",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Mewtwo_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/1/1a/150MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/7/78/150Mewtwo.png/250px-150Mewtwo.png",
    },
    151: {
        number: 151,
        name: "Mew",
        type: "Psychic",
        bulbapedia_url: "https://bulbapedia.bulbagarden.net/wiki/Mew_(Pok%C3%A9mon)",
        thumb: "https://cdn.bulbagarden.net/upload/a/a7/151MS.png",
        img: "https://cdn.bulbagarden.net/upload/thumb/b/b1/151Mew.png/250px-151Mew.png",
    },
}
